// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBc7OT-P0FC7qKtGEAQ_ltoz1NqlUg5n0',
    appId: '1:508248596793:web:586b4025d2684732ad08e8',
    messagingSenderId: '508248596793',
    projectId: 'myshop-aca8d',
    authDomain: 'myshop-aca8d.firebaseapp.com',
    storageBucket: 'myshop-aca8d.appspot.com',
    measurementId: 'G-REGEX9KKD3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBavO2MVPazdZX0G6WR7PBafdxu3MnQVOE',
    appId: '1:508248596793:android:deeda5750f17d74fad08e8',
    messagingSenderId: '508248596793',
    projectId: 'myshop-aca8d',
    storageBucket: 'myshop-aca8d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4iVi0H2sb61hU_aZC9BV4_IFHb0DasxE',
    appId: '1:508248596793:ios:1d9555c5501c0114ad08e8',
    messagingSenderId: '508248596793',
    projectId: 'myshop-aca8d',
    storageBucket: 'myshop-aca8d.appspot.com',
    iosBundleId: 'com.example.myshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4iVi0H2sb61hU_aZC9BV4_IFHb0DasxE',
    appId: '1:508248596793:ios:1d9555c5501c0114ad08e8',
    messagingSenderId: '508248596793',
    projectId: 'myshop-aca8d',
    storageBucket: 'myshop-aca8d.appspot.com',
    iosBundleId: 'com.example.myshop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBc7OT-P0FC7qKtGEAQ_ltoz1NqlUg5n0',
    appId: '1:508248596793:web:dfe92b9d11c30304ad08e8',
    messagingSenderId: '508248596793',
    projectId: 'myshop-aca8d',
    authDomain: 'myshop-aca8d.firebaseapp.com',
    storageBucket: 'myshop-aca8d.appspot.com',
    measurementId: 'G-3GQ92S1MML',
  );
}
